[package]
name = "nixie-clock"
version = "1.0.0"
edition = "2021"
authors = ["NewDawn0 (Tom)"]
license = "MIT"
keywords = ["date", "clock", "time"]
categories = ["command-line-utilities"]

[dependencies]
pad = "0.1.6"
colored = "2"
chrono = "0.4"
simple-scheduler = "0.1.0"
